logging:
  level:
    root: DEBUG
spring:
  flyway:
    baseline-on-migrate: true
    defaultSchema: appdata
    locations:
    - classpath:db
    schemas:
    - appdata
  mvc:
    static-path-pattern: "/resources/**"
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/erentaldb?currentSchema=appdata
    username: postgres
    password: 2005
  application:
    name: erental
